name: Run tests
on: [push, pull_request]

jobs:
  runtests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker build
        shell: bash
        run: docker build .
